### ISSUE TITLE
Try using unicode characters to double the resolution

### ISSUE THREAD

**Issue by pazdera** [pazdera/catpix#3]
We could use only one character for the pixel split into two colours using the Unicode "Upper Half Block" character (U+2580 - ▀ and ▄) with foreground and colouring the rest with background colour.

**Suggested by**: Doodpants and 0x0dea

**Comment by bruno-** [comment]
This would be so awesome! The image resolution would increase 4x!

**Comment by pazdera** [comment]
This feature was added in `0.2.0`, closing.

https://rubygems.org/gems/catpix

Thanks, Bruno, for your help with it!
