### ISSUE TITLE
please document the sytem lib dependencies

### ISSUE THREAD

**Issue by ksilin** [pazdera/catpix#4]
the gem seems to depend on `libmagickcore-dev` and `libmagickwand-dev`. I had installed the regular packages but still could not build the native extensions.

OS: Linux Mint 17.1 Rebecca

thank you.

**Comment by pazdera** [comment]
Hi Konstantin,

Thanks for raising this issue. Those are prerequisites of [rmagick](https://github.com/rmagick/rmagick), a gem that catpix depends on. They describe what you need [here](https://github.com/rmagick/rmagick#prereq).

Let me know if you have any more questions/issues.

**Comment by ksilin** [comment]
Ah, I see, I didn't detangle the transitional dependencies. Thank you for the explanation and the cool tool and sorry for the inconvenience :blush:

**Comment by pazdera** [comment]
No worries at all. There's no harm in asking :-).
