### ISSUE TITLE
Return image instead of printing

### ISSUE THREAD

**Issue by stfnhh** [pazdera/catpix#9]
Would it be possible to return the image as a string instead of printing it directly to the screen?

**Comment by pazdera** [comment]
Hey Stefan,

Sure, it would require rearranging things a little and adding another function to the interface that would return the string instead of printing it.

I'm happy to do it over the weekend.

**Comment by posva** [comment]
@stfnhrrs you can use https://github.com/posva/catimg to do that in the meantime
